{-# OPTIONS --safe #-}
module Iliagda.Dec.Core where

open import Iliagda.Init
open import Iliagda.Morphology
open import Iliagda.Prosody.Core

-- ** decidable equality
unquoteDecl DecEq-Quantity = derive-DecEq [ quote Quantity , DecEq-Quantity ]
unquoteDecl DecEq-Foot = derive-DecEq [ quote Foot , DecEq-Foot ]
unquoteDecl Show-Letter = derive-Show [ quote Letter , Show-Letter ]

show-inj : Injective {A = Letter} _≡_ _≡_ show
show-inj {Ἀ} {Ἀ} refl = refl
show-inj {Ἄ} {Ἄ} refl = refl
show-inj {α} {α} refl = refl
show-inj {ἀ} {ἀ} refl = refl
show-inj {ἁ} {ἁ} refl = refl
show-inj {ἂ} {ἂ} refl = refl
show-inj {ἄ} {ἄ} refl = refl
show-inj {ὰ} {ὰ} refl = refl
show-inj {ά} {ά} refl = refl
show-inj {ᾶ} {ᾶ} refl = refl
show-inj {ᾷ} {ᾷ} refl = refl
show-inj {ε} {ε} refl = refl
show-inj {ἐ} {ἐ} refl = refl
show-inj {ἑ} {ἑ} refl = refl
show-inj {ἔ} {ἔ} refl = refl
show-inj {ἕ} {ἕ} refl = refl
show-inj {έ} {έ} refl = refl
show-inj {ὲ} {ὲ} refl = refl
show-inj {η} {η} refl = refl
show-inj {ῆ} {ῆ} refl = refl
show-inj {ῇ} {ῇ} refl = refl
show-inj {ῃ} {ῃ} refl = refl
show-inj {ἠ} {ἠ} refl = refl
show-inj {ἡ} {ἡ} refl = refl
show-inj {ἢ} {ἢ} refl = refl
show-inj {ἣ} {ἣ} refl = refl
show-inj {ἤ} {ἤ} refl = refl
show-inj {ἦ} {ἦ} refl = refl
show-inj {ἥ} {ἥ} refl = refl
show-inj {Ἥ} {Ἥ} refl = refl
show-inj {ή} {ή} refl = refl
show-inj {ὴ} {ὴ} refl = refl
show-inj {ᾔ} {ᾔ} refl = refl
show-inj {ι} {ι} refl = refl
show-inj {ί} {ί} refl = refl
show-inj {ὶ} {ὶ} refl = refl
show-inj {ἰ} {ἰ} refl = refl
show-inj {ἱ} {ἱ} refl = refl
show-inj {ἳ} {ἳ} refl = refl
show-inj {ἴ} {ἴ} refl = refl
show-inj {ἶ} {ἶ} refl = refl
show-inj {Ἴ} {Ἴ} refl = refl
show-inj {ῖ} {ῖ} refl = refl
show-inj {ϊ} {ϊ} refl = refl
show-inj {ΐ} {ΐ} refl = refl
show-inj {ῒ} {ῒ} refl = refl
show-inj {ο} {ο} refl = refl
show-inj {Ο} {Ο} refl = refl
show-inj {ὀ} {ὀ} refl = refl
show-inj {Ὀ} {Ὀ} refl = refl
show-inj {ὁ} {ὁ} refl = refl
show-inj {ὃ} {ὃ} refl = refl
show-inj {ὄ} {ὄ} refl = refl
show-inj {ὅ} {ὅ} refl = refl
show-inj {ό} {ό} refl = refl
show-inj {ὸ} {ὸ} refl = refl
show-inj {υ} {υ} refl = refl
show-inj {ὐ} {ὐ} refl = refl
show-inj {ὑ} {ὑ} refl = refl
show-inj {ὔ} {ὔ} refl = refl
show-inj {ὖ} {ὖ} refl = refl
show-inj {ὕ} {ὕ} refl = refl
show-inj {ὗ} {ὗ} refl = refl
show-inj {ὺ} {ὺ} refl = refl
show-inj {ύ} {ύ} refl = refl
show-inj {ῦ} {ῦ} refl = refl
show-inj {ϋ} {ϋ} refl = refl
show-inj {ΰ} {ΰ} refl = refl
show-inj {ω} {ω} refl = refl
show-inj {ὠ} {ὠ} refl = refl
show-inj {ὣ} {ὣ} refl = refl
show-inj {ὤ} {ὤ} refl = refl
show-inj {ὥ} {ὥ} refl = refl
show-inj {ὦ} {ὦ} refl = refl
show-inj {ᾤ} {ᾤ} refl = refl
show-inj {ᾧ} {ᾧ} refl = refl
show-inj {ώ} {ώ} refl = refl
show-inj {ὼ} {ὼ} refl = refl
show-inj {ῶ} {ῶ} refl = refl
show-inj {ῳ} {ῳ} refl = refl
show-inj {ῴ} {ῴ} refl = refl
show-inj {ῷ} {ῷ} refl = refl
show-inj {Β} {Β} refl = refl
show-inj {β} {β} refl = refl
show-inj {Γ} {Γ} refl = refl
show-inj {γ} {γ} refl = refl
show-inj {Δ} {Δ} refl = refl
show-inj {δ} {δ} refl = refl
show-inj {Ζ} {Ζ} refl = refl
show-inj {ζ} {ζ} refl = refl
show-inj {Θ} {Θ} refl = refl
show-inj {θ} {θ} refl = refl
show-inj {Κ} {Κ} refl = refl
show-inj {κ} {κ} refl = refl
show-inj {Λ} {Λ} refl = refl
show-inj {ƛ} {ƛ} refl = refl
show-inj {Μ} {Μ} refl = refl
show-inj {μ} {μ} refl = refl
show-inj {Ν} {Ν} refl = refl
show-inj {ν} {ν} refl = refl
show-inj {Ξ} {Ξ} refl = refl
show-inj {ξ} {ξ} refl = refl
show-inj {Π} {Π} refl = refl
show-inj {π} {π} refl = refl
show-inj {Ρ} {Ρ} refl = refl
show-inj {ρ} {ρ} refl = refl
show-inj {ῥ} {ῥ} refl = refl
show-inj {Σ} {Σ} refl = refl
show-inj {σ} {σ} refl = refl
show-inj {ς} {ς} refl = refl
show-inj {Τ} {Τ} refl = refl
show-inj {τ} {τ} refl = refl
show-inj {Φ} {Φ} refl = refl
show-inj {φ} {φ} refl = refl
show-inj {Χ} {Χ} refl = refl
show-inj {χ} {χ} refl = refl
show-inj {Ψ} {Ψ} refl = refl
show-inj {ψ} {ψ} refl = refl
show-inj {᾽} {᾽} refl = refl

instance
  DecEq-Letter : DecEq Letter
  DecEq-Letter ._≟_ _ _ = mapDec show-inj (cong show) $ _ ≟ _
